### Classes for tables in db ###

from typing import Optional
import decimal

from sqlalchemy import BigInteger, Double, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from database import Base

class NutrientI(Base):
    __tablename__ = 'nutrient_i'

    Food_ID: Mapped[str] = mapped_column(String(100), primary_key=True)
    Food_Name: Mapped[Optional[str]] = mapped_column(Text)
    Serving_Size: Mapped[Optional[str]] = mapped_column(Text)
    Weight_g: Mapped[Optional[int]] = mapped_column(Integer)
    Carbohydrates_g: Mapped[Optional[int]] = mapped_column(BigInteger)
    Protein_g: Mapped[Optional[int]] = mapped_column(Integer)
    Fat_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    Fiber_g: Mapped[Optional[int]] = mapped_column(Integer)
    Calories_kcal: Mapped[Optional[int]] = mapped_column(Integer)
    Glycemic_Index: Mapped[Optional[str]] = mapped_column(Text)


class NutrientS(Base):
    __tablename__ = 'nutrient_s'

    food_code: Mapped[str] = mapped_column(String(100), primary_key=True)
    food_name: Mapped[Optional[str]] = mapped_column(Text)
    primarysource: Mapped[Optional[str]] = mapped_column(Text)
    energy_kj: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    energy_kcal: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    carb_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    protein_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    fat_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    freesugar_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    fibre_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    sfa_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    mufa_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    pufa_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    cholesterol_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    calcium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    phosphorus_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    magnesium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    sodium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    potassium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    iron_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    copper_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    selenium_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    chromium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    manganese_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    molybdenum_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    zinc_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vita_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vite_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitd2_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitd3_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitk1_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitk2_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    folate_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitb1_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitb2_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitb3_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitb5_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitb6_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitb7_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitb9_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    vitc_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    carotenoids_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    servings_unit: Mapped[Optional[str]] = mapped_column(Text)
    unit_serving_energy_kj: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_energy_kcal: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_carb_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_protein_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_fat_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_freesugar_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_fibre_g: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_sfa_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_mufa_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_pufa_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_cholesterol_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_calcium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_phosphorus_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_magnesium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_sodium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_potassium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_iron_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_copper_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_selenium_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_chromium_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_manganese_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_molybdenum_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_zinc_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vita_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vite_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitd2_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitd3_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitk1_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitk2_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_folate_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitb1_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitb2_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitb3_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitb5_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitb6_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitb7_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitb9_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_vitc_mg: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
    unit_serving_carotenoids_ug: Mapped[Optional[decimal.Decimal]] = mapped_column(Double(asdecimal=True))
